parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_pgsql'
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '10.0'
                charset: utf8
                mapping_types:
                    _text: text_array
            db_v3:
                driver: 'pdo_pgsql'
                url: '%env(LEGACY_DATABASE_URL)%'
                charset: utf8
        types:
            geography: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
            int_array: 'Doctrine\DBAL\PostgresTypes\IntArrayType'
            text_array: 'Doctrine\DBAL\PostgresTypes\TextArrayType'
            translations: 'App\Doctrine\Types\TranslationsType'
            simple_object: 'App\Doctrine\Types\SimpleObjectType'
            custom_data_collection: 'App\Doctrine\Types\CustomDataCollectionType'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                ST_Distance: 'Jsor\Doctrine\PostGIS\Functions\ST_Distance'
                ST_GeomFromText: 'Jsor\Doctrine\PostGIS\Functions\ST_GeomFromText'
                Trans: 'App\Doctrine\Functions\Trans'
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Finna:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Finna/Entity'
                prefix: 'App\Module\Finna\Entity'
            Ptv:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Ptv/Entity'
                prefix: 'App\Module\Ptv\Entity'
            ServiceTree:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/ServiceTree/Entity'
                prefix: 'App\Module\ServiceTree\Entity'
            UserManagement:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/UserManagement/Entity'
                prefix: 'App\Module\UserManagement\Entity'
