parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '10.0'
        charset: utf8

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geography: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
            text_array: 'Doctrine\DBAL\PostgresTypes\TextArrayType'
            translations: 'App\Doctrine\Types\TranslationsType'
            simple_object: 'App\Doctrine\Types\SimpleObjectType'
            custom_data_collection: 'App\Doctrine\Types\CustomDataCollectionType'
        mapping_types:
            _text: text_array
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                ST_Distance: 'Jsor\Doctrine\PostGIS\Functions\ST_Distance'
                ST_GeomFromText: 'Jsor\Doctrine\PostGIS\Functions\ST_GeomFromText'
                Trans: 'App\Doctrine\Functions\Trans'
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Finna:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Finna/Entity'
                prefix: 'App\Module\Finna\Entity'
            Ptv:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Ptv/Entity'
                prefix: 'App\Module\Ptv\Entity'
            ServiceTree:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/ServiceTree/Entity'
                prefix: 'App\Module\ServiceTree\Entity'
