framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    csrf_protection: ~
    #http_method_override: true

    # Probably legacy definitions but required when FOSRestBundle is enabled (until fixed for Symfony 4)
    templating:
      engines: ['twig']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    serializer:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/src/Resources/config/serialization']
    php_errors:
        log: true

    cache: ~
    assets:
        version_strategy: 'App\Asset\FilemtimeAssetVersionStrategy'
