vich_uploader:
    db_driver: orm
    mappings:
        image:
            uri_prefix: /files/images
            upload_destination: files/images
            namer: vich_uploader.namer_uniqid
        consortium_logo:
            uri_prefix: /files/logos
            upload_destination: files/logos
            namer: vich_uploader.namer_uniqid

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
