user.login:
    path: '/login'
    controller: 'UserAccountsBundle:Account:login'

translation:
    type: annotation
    resource: '../../src/Module/Translation/Controller/'

kirkanta_service_tree:
    type: annotation
    resource: '../../src/Module/ServiceTree/Controller/'

finna_additions:
    type: annotation
    resource: '../../src/Module/Finna/Controller/'

controllers:
    type: annotation
    resource: '../../src/Controller/'

user_management:
    type: annotation
    resource: '../../src/Module/UserManagement/Controller/'

service_tool:
    type: annotation
    resource: '../../src/Module/ServiceMergeTool/Controller/'

entity_routes:
    type: entity_routes
    resource: 'App\Routing\EntityRouteLoader:load'

library_routes:
    type: library_routes
    resource: 'App\Routing\LibraryRouteLoader:load'


# NOTE: Put this last to allow other controllers to override generic functionality.
entity_controller:
    resource: ../../src/Controller/EntityController.php
    type: annotation
