parameters:
    ptv.username: '%env(PTV_USERNAME)%'
    ptv.password: '%env(PTV_PASSWORD)%'
    ptv.api: 'https://api.palvelutietovaranto.trn.suomi.fi/api/V8/'
    ptv.auth_url: 'https://palvelutietovaranto.trn.suomi.fi/connect/token'
