services:
    translator.data_collector:
        class: 'Symfony\Component\Translation\DataCollectorTranslator'
        decorates: 'translator'
        arguments: ['@translator.data_collector.inner']
