App\Entity\ContactInfo:
  attributes: 
    translations:
      groups: ['default', 'index']

App\Entity\ContactInfoData:
  attributes:
    name:
      groups: ['default']
    description:
      groups: ['default']

App\Entity\PhoneNumber:
  attributes:
    number:
      groups: ['default']
