App\Entity\Department:
  attributes:
    translations:
      groups: ['default', 'index']
    id:
      groups: ['default', 'index']

App\Entity\DepartmentData:
  attributes:
    slug:
      groups: ['default', 'index']
    name:
      groups: ['default', 'index']
    description:
      groups: ['default']
