App\Entity\Consortium:
  attributes:
    translations:
      groups: ['default', 'index']
    id:
      groups: ['default', 'index']
    logo:
      groups: ['default', 'index']
    created:
      groups: ['default', 'api_cache']
    modified:
      groups: ['default', 'api_cache']

App\Entity\ConsortiumData:
  attributes:
    name:
      groups: ['default', 'index']
    slug:
      groups: ['default', 'index']
    homepage:
      groups: ['default']
    description:
      groups: ['default']
