App\Entity\NestedImage:
  attributes:
    filename:
      groups: ['default']
    filesize:
      groups: ['default']
    dimensions:
      groups: ['default']
    originalName:
      groups: ['default']
    type:
      groups: ['default']
