App\Entity\ServicePoint:
  attributes:
    translations:
      groups: ['default', 'index']
    id:
      groups: ['default', 'index']
    type:
      groups: ['default', 'index']
    consortium:
      groups: ['default']
    city:
      groups: ['default']
    address:
      groups: ['default']
    mail_address:
      groups: ['mail_address', 'api_cache']
    phone_numbers:
      groups: ['phone_numbers', 'api_cache']
    links:
      groups: ['phone_numbers', 'api_cache']
    email_addresses:
      groups: ['phone_numbers', 'api_cache']
    custom_data:
      groups: ['custom_data', 'api_cache']
    pictures:
      groups: ['pictures', 'api_cache']
    created:
      groups: ['default', 'api_cache']
    modified:
      groups: ['default', 'api_cache']
    buses:
      groups: ['default']
    trains:
      groups: ['default']
    trams:
      groups: ['default']
