App\Entity\ContactInfo:
  attributes:
    translations:
      groups: ['default', 'index']

App\Entity\ContactInfoData:
  attributes:
    name:
      groups: ['default']
    description:
      groups: ['default']

App\Entity\EmailAddress:
  attributes:
    email:
      groups: ['default']
    department:
      groups: ['default', 'index']

App\Entity\PhoneNumber:
  attributes:
    number:
      groups: ['default']
    department:
      groups: ['default', 'index']

App\Entity\WebsiteLink:
  attributes:
    url:
      groups: ['default']
    department:
      groups: ['default', 'index']

App\Module\Finna\Entity\FinnaOrganisationWebsiteLink:
  attributes:
    url:
      groups: ['default', 'index']
    category:
      groups: ['default']
