App\Module\Finna\Entity\FinnaAdditions:
  attributes:
    translations:
      groups: ['default', 'index']
    id:
      groups: ['default', 'index']
    service_point:
      groups: ['default']
    finna_coverage:
      groups: ['default']
    consortium:
      groups: ['default']
    finna_id:
      groups: ['default']
    links:
      groups: ['default']
    custom_data:
      groups: ['custom_data', 'api_cache']

App\Module\Finna\Entity\FinnaAdditionsData:
  attributes:
    usage_info:
      groups: ['default']
    notification:
      groups: ['default']
